name: Update README
on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Latest Stats
        run: curl -o README.md https://leetcode-flask.onrender.com/leetcode-stats/Krishna_Revanth_Karra.svg

      - name: Commit and Push Changes
        run: |
          git config --global user.name "Krishnarevanthkarra"
          git config --global user.email "krishnarevanth.ic@gmail.com"
          git add README.md
          git commit -m "Updated LeetCode stats"
          git push
